name: "CI"

env:
  DOTENV_CONFIG_PATH: "./.env.example"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    services:
      # Label used to access the service container
      localfhenix:
        options: --name localfhenix
        image: ghcr.io/fhenixprotocol/localfhenix:v0.3.2-alpha.4
        ports:
          - 42000:3000
          - 42069:8547
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Pnpm"
        uses: "pnpm/action-setup@v3"
        with:
          version: "9"

      - name: "Install Node.js"
        uses: "actions/setup-node@v4"
        with:
          cache: "pnpm"
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "pnpm install"

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "pnpm typechain"

      - name: "Make Money"
        run: "pnpm fhenix:faucet"

      - name: "Test the contracts using Hardhat Network"
        run: "pnpm test:hardhat"

      - name: "Test the contract using LocalFhenix"
        run: "pnpm test:localfhenix"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
